export const RSS_FETCH = 'RSS_FETCH'
export const FETCH_RSS_BEGIN   = 'FETCH_RSS_BEGIN';
export const FETCH_RSS_SUCCESS = 'FETCH_RSS_SUCCESS';
export const FETCH_RSS_FAILURE = 'FETCH_RSS_FAILURE';
export const DELETE_EVENT = 'DELETE_EVENT';